# Generated by Django 3.2.6 on 2021-08-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_auto_20210826_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='phone',
            field=models.CharField(default='000000', max_length=13, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
